server:
  context-path: /cmfz
  jsp-servlet:
    init-parameters:
      development: true
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    data-username: root
    data-password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
    encoding:
      charset: utf-8
      force: true
mybatis:
  type-aliases-package: com.baizhi.cmfz.entity
  mapper-locations: com/baizhi/cmfz/dao/*.xml
